### PR TITLE
Enhancement: jgt_tools and travis

### PR DESCRIPTION
**Pull request by bradsbrown**
Integrate `jgt_tools` into this package, and set up travis integration.

### CODE REVIEW

**Comment by bradsbrown** [comment]
Docs available at https://bradsbrown.github.io/jolly_github_toolbelt/

**Review by brolewis — APPROVED** [review]
LGTM

**Review by arounkles — APPROVED** [review]
Looks good here. :+1:

**Comment by arounkles** [comment]
Didn't actually mean to remove all the assignees. Using a new-to-me github client app on my phone. Oops.

Merged anyway, so I suppose no harm done.

**Pull request merged**
